# Creating a sample Dockerfile to build a Docker image with apache, mailu, and mySQL
version: "2"

services:
    apache:
        build: apache 
        ports:
        - "8001:80"
        
    mysql:
        build: mysql
        ports:
        - "8002:80"
        
    mailu:
        build: mailu
        ports:
        - "8000:80"
