# Creating a sample Dockerfile to build a Docker image with apache, postfix, and mySQL


services:
    apache mysql:
        build: apache mysql
        ports:
        -   "8001:80"
        
    postfix:
        build: postfix
        ports:
        -   "8000:80"
