# Creating a sample Dockerfile to build a Docker image with apache, postfix, and mySQL

FROM ubuntu:18.04

services:
    apache:
        build:apache
        ports:
        -   "8001:80"
        
    mySQL:
        build: mySQL
        ports:
        -   "8002:80"
        
    postfix:
        build: postfix
        ports:
        -   "8000:80"
